language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

before_install:
  - composer self-update

cache:
  directories:
    - $HOME/.composer/cache

install: composer update --prefer-dist --no-interaction

script:
  - ./vendor/bin/phing build

after_success:
  - travis_retry php vendor/bin/coveralls
